description = "自然言語の機能説明から機能仕様を作成または更新します。"

prompt = """
---
description: 自然言語の機能説明から機能仕様を作成または更新します。
---

日本語で出力すること。
ユーザー入力は、エージェントから直接提供されるか、コマンド引数として提供されます - プロンプトを進める前に（空でない場合）それを**必ず**考慮に入れる必要があります。

ユーザー入力:

$ARGUMENTS

トリガーメッセージでユーザーが `/specify` の後に入力したテキストが機能説明です。 `{{args}}` が以下に文字通り表示されていても、この会話で常に利用可能であると想定してください。ユーザーが空のコマンドを提供しない限り、それを繰り返すようにユーザーに依頼しないでください。

その機能説明を前提として、これを実行してください：

1. リポジトリのルートからスクリプト `.specify/scripts/bash/create-new-feature.sh --json "{{args}}"` を実行し、そのJSON出力を解析してBRANCH_NAMEとSPEC_FILEを取得します。すべてのファイルパスは絶対パスである必要があります。
  **重要** このスクリプトは一度だけ実行する必要があります。JSONはターミナルに出力として提供されます - 探している実際のコンテンツを取得するには、常にそれを参照してください。
2. 必要なセクションを理解するために `.specify/templates/spec-template.md` を読み込みます。
3. テンプレート構造を使用して仕様をSPEC_FILEに書き込み、セクションの順序と見出しを維持しながら、プレースホルダーを機能説明（引数）から派生した具体的な詳細に置き換えます。
4. ブランチ名、仕様ファイルパス、および次のフェーズの準備ができたことを報告します。

注：スクリプトは、書き込む前に新しいブランチを作成してチェックアウトし、仕様ファイルを初期化します。
"""